name: fetch upstream 
on:
  #schedule:
  #  - cron: '0 */1 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: alexta69
          base: master
          head: master
          auto_approve: true
          token: ${{ secrets.TOKEN }}
